#!/bin/bash

#mkdir -p /tmp/nbgraderExchange

jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --user formgrader/main --section=tree

jupyter serverextension enable --sys-prefix --py nbgrader
