#!/bin/bash

jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --user formgrader/main --section=tree

#If we're not using JupyterHub, do we need this?
#jupyter serverextension enable --sys-prefix --py nbgrader
